export const strings = {
  common: {
    cancel: "ביטול",
    confirm: "אישור",
    save: "שמור",
    delete: "מחק",
    close: "סגור",
    undo: "בטל",
    loading: "טוען…",
    saving: "שומר…",
    decrement: "פחות",
    increment: "עוד",
  },
  validation: {
    required: "שדה חובה",
    nameRequired: "השם לא יכול להיות ריק",
    positiveAmount: "הכמות חייבת להיות חיובית",
    emailInvalid: "כתובת אימייל לא תקינה",
  },
  welcome: {
    title: "נעים להכיר 👋",
    subtitle: "עוד רגע אופים. ספרו לנו רק מי אתם:",
    nameLabel: "שם פרטי",
    namePlaceholder: "איך קוראים לך?",
    emailLabel: "אימייל",
    privacyNote:
      "נשתמש בזה רק כדי להבין איך אופים עם כיכר ולעדכן אתכם על שיפורים. בלי ספאם.",
    cta: "מתחילים לאפות 🍞",
  },
  install: {
    title: "כיכר על מסך הבית",
    body: "כמו אפליקציה אמיתית — והבייקים והמתכונים שלכם נשמרים לאורך זמן.",
    installCta: "התקנה",
    iosCta: "איך מתקינים?",
    fbTitle: "אתם בדפדפן של פייסבוק",
    fbBody: "כדי להתקין את כיכר פתחו בדפדפן הרגיל: תפריט ⋯ למעלה ← ״פתיחה בדפדפן חיצוני״.",
    dismissLabel: "סגירת הצעת ההתקנה",
    guideTitle: "התקנה על אייפון",
    guideStep1: "לחצו על כפתור השיתוף בסרגל הדפדפן",
    guideStep2: "גללו ובחרו ״הוסף למסך הבית״",
    guideStep3: "אישור — וכיכר מחכה לכם במסך הבית",
  },
  home: {
    wordmark: "כיכר",
    subtitle: "מה אופים היום?",
    startBaking: "התחל אפייה",
    startBakingAlt: "אפייה חדשה",
    myRecipes: "המתכונים שלי",
  },
  recipes: {
    pageTitle: "המתכונים שלי",
    newRecipe: "+ מתכון חדש",
    backToHome: "חזרה",
    emptyTitle: "עדיין אין מתכונים",
    emptyDescription: "הוסף את המתכון הראשון שלך כדי להתחיל",
  },
  bakeStub: {
    title: "מצב אפייה — בקרוב",
    description: "הזרימה הזאת תיכנס בקרוב. בינתיים, תכין את המתכונים שלך.",
  },
  bake: {
    chooserTitle: "בייק חדש",
    chooserRecipeHeading: "איזה סוג לחם?",
    myBadge: "שלי",
    // Banner (compact, on top of HomeScreen when there's an active bake)
    resumeBannerLabel: "ממשיכים",
    resumeBannerStage: (stageNumber: number, totalStages: number) =>
      `שלב ${stageNumber} מתוך ${totalStages}`,
    resumeBannerContinue: "המשך",
    resumeBannerStop: "סיים בייק",
    // Dialog: stopping the current bake (from the banner)
    stopTitle: "להפסיק את הבייק?",
    stopDescription: (recipeName: string) =>
      `ההתקדמות של ״${recipeName}״ תאבד.`,
    stopConfirm: "כן, להפסיק",
    stopCancel: "לא, להמשיך",
    // Dialog: starting a new bake while one is active (from the chooser)
    replaceTitle: "להחליף בייק?",
    replaceDescription: (recipeName: string) =>
      `הבייק הנוכחי של ״${recipeName}״ יסתיים.`,
    replaceConfirm: "כן, להחליף",
    replaceCancel: "ביטול",
    stagePlaceholderTitle: (stageNumber: number) => `שלב ${stageNumber} — בקרוב`,
    stagePlaceholderBackToHome: "חזרה למסך הבית",
    doneTitle: "הלחם מוכן!",
    doneBlurb: "תהנו מהפרי של 24–48 שעות עבודה. אחרי שעת הקירור על הרשת — הקרום עכשיו בשיאו.",
    doneButton: "סיימתי",
    // Stage screen
    stageCounter: (current: number, total: number) => `${current}/${total}`,
    stageNext: (nextName: string) => `הבא — ${nextName}`,
    stageNextShort: "הבא",
    stagePrev: "חזרה",
    stageMenuLabel: "תפריט",
    stageFinishFold: "סיימתי קיפול",
    stageDone: "סיימתי",
    // Optional timer
    timerStart: "התחל טיימר",
    timerPause: "השהה",
    timerResume: "המשך",
    timerReset: "אפס",
    timerFinished: "הסתיים",
    // Dough temp shadow estimate (feature 22)
    doughTemp: {
      prompt: "יש מד-חום? מדדו את טמפ׳ הבצק",
      measured: "מדדתי",
      fieldLabel: "טמפ׳ הבצק",
      save: "שמירה",
      cancel: "ביטול",
      edit: "עריכה",
      remove: "הסרת המדידה",
      rangeError: "טווח סביר: 18–35°C",
      shadowPrefix: (temp: string) => `לפי טמפ׳ הבצק (${temp}°): `,
      hintEarly: "התחילו לבדוק מוקדם מהרגיל.",
      hintLater: "יש לכם יותר זמן מהרגיל.",
      hintSimilar: "קרוב לתחזית הרגילה.",
      signsRule: "הסימנים על הבצק עדיין קובעים.",
    },
    // Rescue paths (feature 20)
    rescueTrigger: "משהו לא מסתדר?",
    rescueSheetTitle: "אבחון מהיר",
    rescueSigns: "הסימנים",
    rescueSteps: "מה עושים",
    flourTypeLabels: {
      white: "קמח לבן",
      wholeWheat: "קמח מלא",
      rye: "קמח שיפון",
      speltWhite: "קמח כוסמין לבן",
      speltWhole: "קמח כוסמין מלא",
      other: "קמח אחר",
    },
    bakingMethod: {
      selectorTitle: "באיזה כלי תאפה?",
      methods: {
        "closed-vessel": {
          title: "סיר/כלי סגור",
          description:
            "סיר ברזל יצוק, סיר נירוסטה עם מכסה, או תבנית עם קערה הפוכה. הכלי אוטם את האדים.",
        },
        "open-with-steam": {
          title: "אפייה פתוחה + תבנית אדים",
          description:
            "תבנית/אבן/פלדה/סיר נירוסטה ללא מכסה, עם תבנית מים נפרדת למטה לאדים.",
        },
        other: {
          title: "אחר / לא בטוח",
          description: "ההוראות הגנריות יעזרו לכם להבין מה לעשות לפי הציוד שלכם.",
        },
      },
      genericSafetyWarning:
        "ודאו שכל הציוד שאתם משתמשים בו עמיד לחום של 250°C. מתכת (נירוסטה) או קרמיקה איכותית בטוחות. זכוכית רגילה תיסדק. פלסטיק יימס.",
    },
  },
  form: {
    nameLabel: "שם המתכון",
    namePlaceholder: "לחם של שישי",
    flourBreakdownTitle: "פירוט קמחים",
    flourWhite: "לבן",
    flourWholeWheat: "מלא",
    flourRye: "שיפון",
    flourSpeltWhite: "כוסמין לבן",
    flourSpeltWhole: "כוסמין מלא",
    flourSumOk: "סה״כ: ",
    flourSumShort: "חסר",
    flourSumOver: "עודף",
    flourWeight: "משקל קמח",
    flourWeightHintMedium: "500g · ככר בינונית (~1kg בצק)",
    flourWeightHintLarge: "750g · ככר גדולה (~1.5kg בצק)",
    hydration: "הידרציה",
    hydrationFlourNote:
      "קמח לבן רגיל מהסופר (~10.5% חלבון) סופג פחות מים — איתו הישארו סביב 70–72%. קמח לחם (12%+ חלבון) מחזיק גם 75% ומעלה.",
    salt: "מלח",
    levain: "שאור",
    kitchenTemp: "טמפ׳ מטבח",
    saveButton: "שמור",
    cancelButton: "ביטול",
    inclusionsTitle: "תוספות (אופציונלי)",
    inclusionsAdd: "+ הוסף תוספת",
    inclusionName: "שם",
    inclusionNamePlaceholder: "זיתים שחורים",
    inclusionAmount: "כמות",
    unitGrams: "גרם",
  },
  bakeConfirm: {
    title: "מוכן לאפות?",
    quantities: "כמויות לבייק",
    flour: "קמח",
    water: "מים",
    levain: "שאור",
    salt: "מלח",
    tempLabel: "טמפ׳ מטבח",
    timingHeading: "זמנים משוערים",
    timingSuffix: "(תלוי טמפ׳)",
    startButton: "התחל בייק",
    recommendedNote: "כמויות מומלצות",
    editButton: "ערוך מתכון",
    savedReturnToast: "המתכון נשמר — בחר אותו כאן להתחלת הבייק",
  },
  starterGate: {
    // Gate screen — the yes/no question
    gateTitle: "לפני שמתחילים",
    gateQuestion: "הסטארטר שלך בשיא?",
    gateEducationBlurb:
      "סטארטר בשיא הוכפל בנפח, מלא בועות, ריחו חמצמץ-מתוק, ועובר מבחן ציפה (float test).",
    gateCta_yes: "כן, הסטארטר בשיא",
    gateCta_no: "לא, צריך לתכנן",
    // Schedule screen — planning path
    scheduleTitle: "מתכננים את הבייק",
    scheduleReadyLabel: "מתי הלחם צריך להיות מוכן?",
    scheduleContextLine: (hours: number) =>
      `מהאכלת הסטארטר ועד לחם מוכן — כ-${hours} שעות`,
    schedulePillEarliest: "הכי מוקדם",
    scheduleTempLabel: "טמפ׳ מטבח (°C)",
    scheduleTooSoon: (minDate: string) =>
      `המינימום לבייק זה הוא ${minDate}. הסטארטר + הבייק לוקחים לפחות 38 שעות.`,
    scheduleDismiss: "הבנתי, אחזור מאוחר יותר",
    // Feeding window card
    feedCardTitle: "תוכנית האכלה",
    feedCardFeedLabel: "האכלת הסטארטר",
    feedCardPeakLabel: "הסטארטר יגיע לשיא",
    feedCardDurationBridge: (hours: number) => `כ-${hours} שעות`,
    feedCardTimeDisclaimer: "הזמן הוא הערכה — הסטארטר עצמו יגיד לך מתי הוא מוכן",
    feedCardReadinessTitle: "איך יודעים שהסטארטר מוכן?",
    feedCardReadinessSigns:
      "הוכפל בנפח · מלא בועות · ריח חמצמץ-מתוק · שקוע מעט בפסגה · עובר מבחן ציפה (float test)",
    feedCardCalcNote: (temp: number) => `ההערכה מחושבת לפי ${temp}°C`,
    // Peak explainer — planner toggle trigger + sheet (feature 13)
    peakInfoTrigger: "מה זה בשיא?",
    peakInfoAriaLabel: "פתח הסבר — מה זה סטארטר בשיא",
    peakSheetTitle: "סטארטר בשיא — 4 הסימנים",
    peakSign1: "הוכפל בנפח מאז ההאכלה האחרונה",
    peakSign2: "מלא בועות אוויר",
    peakSign3: "ריח חמצמץ-מתוק (לא חומצי חד)",
    peakSign4: "עובר מבחן ציפה — כפית בכוס מים, הסטארטר צף",
    peakImageAlt: "שלושה מצבי סטארטר: שטוח לפני השיא, מבעבע בשיא, קרוס אחרי השיא",
  },
  bakeScheduler: {
    headerTitle: "תכנון הבייק",
    planningTitle: "תכננו את הבייק",
    planningSubtitle: "הגדירו את התנאים והזמנים שמתאימים לכם",
    backToChooser: "חזרה",
    starterLabel: "הסטארטר כבר בשיא?",
    starterYes: "כן",
    starterNo: "לא",
    readyQuestion: "מתי שהלחם ייצא מהתנור?",
    earliest: "הכי מוקדם",
    tempQuestion: "מהי טמפרטורת החדר?",
    tempHint: "חורף 20–24° · קיץ 24–27°",
    tempImportantHint: "הטמפרטורה קובעת את כל הזמנים — כדאי למדוד ולא לנחש",
    scheduleSectionTitle: "תכננו את זמני הבייק",
    scheduleSectionSubtitle: "בחרו תבנית מומלצת או כווננו ידנית",
    presetRowLabel: "התחל מתבנית",
    presetReadyLabel: (day: string, time: string) => `${day} · ${time}`,
    advancedDisclosureOpen: "לכוונן בעצמי",
    advancedDisclosureClose: "סגור כוונון",
    presets: {
      fast:        { name: "מהיר",          hint: "מוכן הכי מהר · טעם עדין" },
      classic:     { name: "קלאסי",         hint: "לילה במקרר · מוכן בבוקר" },
      classicLate: { name: "קלאסי מאוחר",  hint: "לילה ארוך · מוכן לקראת ערב" },
      long:        { name: "ארוך",           hint: "התפחה ממושכת · חמצמץ ועשיר" },
      manual:      { name: "לכוונן בעצמי",  hint: "שלטו בזמנים ויחס האכלת הסטארטר" },
    },
    ratioControl: {
      label: "יחס בניית שאור (levain)",
      hint: (feedHour: string) => `שיא ב-${feedHour}`,
    },
    directionEnd: "מתי לסיים",
    directionStart: "מתי להתחיל",
    readyQuestionStart: "מתי מתחילים?",
    contextLineStart: (hours: number) => `הלחם יהיה מוכן בעוד כ-${hours} שעות`,
    readyResultLabel: (label: string) => `הלחם מוכן ב: ${label}`,
    contextLine: (hours: number) => `הבייק ייקח כ-${hours} שעות`,
    // Inline retard editing on the timeline
    retardSliderLabel: "אורך ההתפחה במקרר",
    retardOverflowNote: (label: string) =>
      `כדי להספיק התפחה כזו, הלחם ייצא ב-${label}`,
    // Timeline
    timelineTitle: "ציר הזמן של הבייק",
    timelineSubtitle: "מתי להתחיל כל שלב",
    timelineEstimateNote: "⏱ זמנים משוערים — עשויים להשתנות לפי הטמפרטורה והסטארטר",
    coolingTip: "מומלץ לצנן כ-שעה לפני חיתוך — חיתוך חם הורס את הפירור",
    // Per-step copy (key matches BakeStepKey). desc may be omitted when computed from duration.
    timelineSteps: {
      build: { label: "בניית שאור (levain)", desc: "ריענון הסטארטר עד לשיא" },
      mix: { label: "ערבוב", desc: "אוטוליזה 45 דק׳ + לישה 15 דק׳" },
      bulk: { label: "תסיסה ראשונית", desc: "כולל קיפולים" },
      shape: { label: "עיצוב הבצק", desc: "עיצוב + מנוחת ביניים · כ-35 דק׳" },
      retard: { label: "התפחה במקרר", desc: "בלילה" },
      preheat: { label: "חימום התנור והכלי", desc: "כ-45 דקות" },
      bake: { label: "הכנסת הבצק לתנור", desc: "מכוסה 20 דק׳ + חשוף 22 דק׳" },
      ready: { label: "הלחם מוכן" },
    },
    tooSoon: (minDate: string) => `המוקדם ביותר: ${minDate}`,
    startButton: "התחל בייק",
    compactSummary: {
      feedLabel: "בניית שאור (levain)",
      activeWindowLabel: "עבודה אקטיבית",
      readyLabel: "הלחם מוכן",
      showTimeline: "הצג את כל השלבים",
    },
  },
  validationCopy: {
    nameRequired: "שדה חובה",
    flourSumWrong: (current: number) =>
      `סה״כ הקמחים חייב להיות 100% (כרגע: ${current.toFixed(1)}%)`,
    hydrationRange: "הידרציה צריכה להיות בין 50% ל-100%",
    saltRange: "מלח צריך להיות בין 0% ל-5%",
    levainRange: "שאור צריך להיות בין 0% ל-40%",
    flourWeightRange: "משקל קמח חייב להיות בין 100g ל-1500g",
    tempRange: "טמפ׳ צריכה להיות בין 10°C ל-40°C",
    inclusionNameRequired: "שם התוספת לא יכול להיות ריק",
    inclusionAmountPositive: "כמות התוספת חייבת להיות חיובית",
  },
  starterTracker: {
    grams: {
      starterLabel: "סטארטר",
      flourLabel: "קמח",
      waterLabel: "מים",
      unit: "גרם",
    },
    validation: {
      ratioRequired: "בחרו יחס האכלה",
      dateRequired: "תאריך ההאכלה הוא שדה חובה",
      gramsNegative: "הכמות לא יכולה להיות שלילית",
    },
    list: {
      pageTitle: "מעקב סטארטר",
      backToHome: "חזרה",
      newFeeding: "+ האכלה חדשה",
      loadErrorMessage: "משהו השתבש בטעינת ההיסטוריה",
      retry: "נסה שוב",
    },
    empty: {
      emptyTitle: "עדיין לא תיעדת האכלות",
      emptyDescription: "הוסף את ההאכלה הראשונה שלך כדי להתחיל לעקוב",
      newFeeding: "+ האכלה ראשונה",
    },
  },
  feedback: {
    fabLabel: "שליחת פידבק",
    title: "שליחת פידבק",
    typeLabel: "סוג",
    typeBug: "באג",
    typeFeature: "הצעה לפיצ׳ר",
    typeQuestion: "שאלה",
    typeOther: "אחר",
    nameLabel: "שם (אופציונלי)",
    namePlaceholder: "השם שלך",
    descriptionLabel: "תיאור",
    descriptionPlaceholder: "תאר את הבעיה או ההצעה…",
    addImage: "הוסף תמונה",
    removeImage: "הסר תמונה",
    submit: "שלח פידבק",
    submitting: "שולח…",
    successToast: "הפידבק נשלח, תודה!",
    errorMessage: "שליחה נכשלה — נסה שוב",
  },
} as const;
