export const strings = {
  common: {
    cancel: "ביטול",
    confirm: "אישור",
    save: "שמור",
    delete: "מחק",
    close: "סגור",
    undo: "בטל",
    loading: "טוען…",
    saving: "שומר…",
    decrement: "פחות",
    increment: "עוד",
  },
  validation: {
    required: "שדה חובה",
    nameRequired: "השם לא יכול להיות ריק",
    positiveAmount: "הכמות חייבת להיות חיובית",
  },
  home: {
    wordmark: "כיכר",
    subtitle: "מה אופים היום?",
    startBaking: "התחל אפייה",
    myRecipes: "המתכונים שלי",
  },
  recipes: {
    pageTitle: "המתכונים שלי",
    newRecipe: "+ מתכון חדש",
    backToHome: "חזרה",
    emptyTitle: "עדיין אין מתכונים",
    emptyDescription: "הוסף את המתכון הראשון שלך כדי להתחיל",
  },
  bakeStub: {
    title: "מצב אפייה — בקרוב",
    description: "הזרימה הזאת תיכנס בקרוב. בינתיים, תכין את המתכונים שלך.",
  },
  form: {
    nameLabel: "שם המתכון",
    namePlaceholder: "לחם של שישי",
    flourBreakdownTitle: "פירוט קמחים",
    flourWhite: "לבן",
    flourWholeWheat: "מלא",
    flourRye: "שיפון",
    flourOther: "אחר",
    flourSumOk: "סה״כ: ",
    flourSumShort: "חסר",
    flourSumOver: "עודף",
    hydration: "הידרציה",
    salt: "מלח",
    levain: "שאור",
    kitchenTemp: "טמפ׳ מטבח",
    saveButton: "שמור",
    cancelButton: "ביטול",
    inclusionsTitle: "תוספות (אופציונלי)",
    inclusionsAdd: "+ הוסף תוספת",
    inclusionName: "שם",
    inclusionNamePlaceholder: "זיתים שחורים",
    inclusionAmount: "כמות",
    unitGrams: "גרם",
  },
  validationCopy: {
    nameRequired: "שדה חובה",
    flourSumWrong: (current: number) =>
      `סה״כ הקמחים חייב להיות 100% (כרגע: ${current.toFixed(1)}%)`,
    hydrationRange: "הידרציה צריכה להיות בין 50% ל-100%",
    saltRange: "מלח צריך להיות בין 0% ל-5%",
    levainRange: "שאור צריך להיות בין 0% ל-40%",
    tempRange: "טמפ׳ צריכה להיות בין 10°C ל-40°C",
    inclusionNameRequired: "שם התוספת לא יכול להיות ריק",
    inclusionAmountPositive: "כמות התוספת חייבת להיות חיובית",
  },
} as const;
