export const strings = {
  common: {
    cancel: "ביטול",
    confirm: "אישור",
    save: "שמור",
    delete: "מחק",
    close: "סגור",
    undo: "בטל",
    loading: "טוען…",
    saving: "שומר…",
    decrement: "פחות",
    increment: "עוד",
  },
  validation: {
    required: "שדה חובה",
    nameRequired: "השם לא יכול להיות ריק",
    positiveAmount: "הכמות חייבת להיות חיובית",
  },
  home: {
    wordmark: "כיכר",
    subtitle: "מה אופים היום?",
    startBaking: "התחל אפייה",
    startBakingAlt: "אפייה חדשה",
    myRecipes: "המתכונים שלי",
  },
  recipes: {
    pageTitle: "המתכונים שלי",
    newRecipe: "+ מתכון חדש",
    backToHome: "חזרה",
    emptyTitle: "עדיין אין מתכונים",
    emptyDescription: "הוסף את המתכון הראשון שלך כדי להתחיל",
  },
  bakeStub: {
    title: "מצב אפייה — בקרוב",
    description: "הזרימה הזאת תיכנס בקרוב. בינתיים, תכין את המתכונים שלך.",
  },
  bake: {
    chooserTitle: "בייק חדש",
    chooserRecipeHeading: "איזה סוג לחם?",
    myBadge: "שלי",
    // Banner (compact, on top of HomeScreen when there's an active bake)
    resumeBannerLabel: "ממשיכים",
    resumeBannerStage: (stageNumber: number, totalStages: number) =>
      `שלב ${stageNumber} מתוך ${totalStages}`,
    resumeBannerContinue: "המשך",
    resumeBannerStop: "סיים בייק",
    // Dialog: stopping the current bake (from the banner)
    stopTitle: "להפסיק את הבייק?",
    stopDescription: (recipeName: string) =>
      `ההתקדמות של ״${recipeName}״ תאבד.`,
    stopConfirm: "כן, להפסיק",
    stopCancel: "לא, להמשיך",
    // Dialog: starting a new bake while one is active (from the chooser)
    replaceTitle: "להחליף בייק?",
    replaceDescription: (recipeName: string) =>
      `הבייק הנוכחי של ״${recipeName}״ יסתיים.`,
    replaceConfirm: "כן, להחליף",
    replaceCancel: "ביטול",
    stagePlaceholderTitle: (stageNumber: number) => `שלב ${stageNumber} — בקרוב`,
    stagePlaceholderBackToHome: "חזרה למסך הבית",
    doneTitle: "הלחם מוכן!",
    doneBlurb: "תהנו מהפרי של 24–48 שעות עבודה. הקרום הכי טוב אחרי לפחות שעה של קירור על רשת.",
    doneButton: "סיימתי",
    // Stage screen
    stageCounter: (current: number, total: number) => `${current}/${total}`,
    stageNext: (nextName: string) => `הבא — ${nextName}`,
    stageNextShort: "הבא",
    stagePrev: "חזרה",
    stageMenuLabel: "תפריט",
    stageFinishFold: "סיימתי קיפול",
    stageDone: "סיימתי",
    // Optional timer
    timerStart: "התחל טיימר",
    timerPause: "השהה",
    timerResume: "המשך",
    timerReset: "אפס",
    timerFinished: "הסתיים",
    flourTypeLabels: {
      white: "קמח לבן",
      wholeWheat: "קמח מלא",
      rye: "קמח שיפון",
      other: "קמח אחר",
    },
    bakingMethod: {
      selectorTitle: "באיזה כלי תאפה?",
      methods: {
        "closed-vessel": {
          title: "סיר/כלי סגור",
          description:
            "סיר ברזל יצוק, סיר נירוסטה עם מכסה, או תבנית עם קערה הפוכה. הכלי אוטם את האדים.",
        },
        "open-with-steam": {
          title: "אפייה פתוחה + תבנית אדים",
          description:
            "תבנית/אבן/פלדה/סיר נירוסטה ללא מכסה, עם תבנית מים נפרדת למטה לאדים.",
        },
        other: {
          title: "אחר / לא בטוח",
          description: "ההוראות הגנריות יעזרו לכם להבין מה לעשות לפי הציוד שלכם.",
        },
      },
      genericSafetyWarning:
        "ודאו שכל הציוד שאתם משתמשים בו עמיד לחום של 250°C. מתכת (נירוסטה) או קרמיקה איכותית בטוחות. זכוכית רגילה תיסדק. פלסטיק יימס.",
    },
  },
  form: {
    nameLabel: "שם המתכון",
    namePlaceholder: "לחם של שישי",
    flourBreakdownTitle: "פירוט קמחים",
    flourWhite: "לבן",
    flourWholeWheat: "מלא",
    flourRye: "שיפון",
    flourOther: "אחר",
    flourSumOk: "סה״כ: ",
    flourSumShort: "חסר",
    flourSumOver: "עודף",
    flourWeight: "משקל קמח",
    flourWeightHintMedium: "500g · ככר בינונית (~1kg בצק)",
    flourWeightHintLarge: "750g · ככר גדולה (~1.5kg בצק)",
    hydration: "הידרציה",
    salt: "מלח",
    levain: "שאור",
    kitchenTemp: "טמפ׳ מטבח",
    saveButton: "שמור",
    cancelButton: "ביטול",
    inclusionsTitle: "תוספות (אופציונלי)",
    inclusionsAdd: "+ הוסף תוספת",
    inclusionName: "שם",
    inclusionNamePlaceholder: "זיתים שחורים",
    inclusionAmount: "כמות",
    unitGrams: "גרם",
  },
  bakeConfirm: {
    title: "מוכן לאפות?",
    quantities: "כמויות לבייק",
    flour: "קמח",
    water: "מים",
    levain: "שאור",
    salt: "מלח",
    tempLabel: "טמפ׳ מטבח",
    timingHeading: "זמנים משוערים",
    timingSuffix: "(תלוי טמפ׳)",
    startButton: "התחל בייק",
    recommendedNote: "כמויות מומלצות",
    editButton: "ערוך מתכון",
    savedReturnToast: "המתכון נשמר — בחר אותו כאן להתחלת הבייק",
  },
  starterGate: {
    // Gate screen — the yes/no question
    gateTitle: "לפני שמתחילים",
    gateQuestion: "הסטארטר שלך בשיא?",
    gateEducationBlurb:
      "סטארטר בשיא הוכפל בנפח, מלא בועות, ריחו חמצמץ-מתוק, ועובר מבחן ציפה (float test).",
    gateCta_yes: "כן, הסטארטר בשיא",
    gateCta_no: "לא, צריך לתכנן",
    // Schedule screen — planning path
    scheduleTitle: "מתכננים את הבייק",
    scheduleReadyLabel: "מתי הלחם צריך להיות מוכן?",
    scheduleContextLine: (hours: number) =>
      `מהאכלת הסטארטר ועד לחם מוכן — כ-${hours} שעות`,
    schedulePillEarliest: "הכי מוקדם",
    scheduleTempLabel: "טמפ׳ מטבח (°C)",
    scheduleTooSoon: (minDate: string) =>
      `המינימום לבייק זה הוא ${minDate}. הסטארטר + הבייק לוקחים לפחות 38 שעות.`,
    scheduleDismiss: "הבנתי, אחזור מאוחר יותר",
    // Feeding window card
    feedCardTitle: "תוכנית האכלה",
    feedCardFeedLabel: "האכלת הסטארטר",
    feedCardPeakLabel: "הסטארטר יגיע לשיא",
    feedCardDurationBridge: (hours: number) => `כ-${hours} שעות`,
    feedCardTimeDisclaimer: "הזמן הוא הערכה — הסטארטר עצמו יגיד לך מתי הוא מוכן",
    feedCardReadinessTitle: "איך יודעים שהסטארטר מוכן?",
    feedCardReadinessSigns:
      "הוכפל בנפח · מלא בועות · ריח חמצמץ-מתוק · שקוע מעט בפסגה · עובר מבחן ציפה (float test)",
    feedCardCalcNote: (temp: number) => `ההערכה מחושבת לפי ${temp}°C`,
  },
  bakeScheduler: {
    headerTitle: "תכנון הבייק",
    backToChooser: "חזרה",
    starterLabel: "הסטארטר כבר בשיא?",
    starterYes: "כן",
    starterNo: "לא",
    readyQuestion: "מתי הלחם צריך להיות מוכן?",
    earliest: "הכי מוקדם",
    tempQuestion: "מה הטמפרטורה בחלל?",
    tempHint: "חורף 20–24° · קיץ 24–27°",
    contextLine: (hours: number) => `הבייק ייקח כ-${hours} שעות`,
    // Timeline
    timelineTitle: "ציר הזמן של הבייק",
    timelineSubtitle: "מתי להתחיל כל שלב",
    coolingTip: "מומלץ לצנן כ-שעה לפני חיתוך — חיתוך חם הורס את הפירור",
    // Per-step copy (key matches BakeStepKey). desc may be omitted when computed from duration.
    timelineSteps: {
      feed: { label: "האכלת הסטארטר", desc: "עד שהסטארטר מגיע לשיא" },
      levain: { label: "בניית השאור" },
      mix: { label: "ערבוב", desc: "אוטוליזה + לישה" },
      bulk: { label: "תסיסה ראשונית", desc: "כולל קיפולים" },
      shapeRetard: { label: "עיצוב + התפחה בקירור", desc: "עיצוב, ואז ~12 שעות בקירור (לילה)" },
      preheat: { label: "חימום התנור והכלי", desc: "כ-45 דקות" },
      bake: { label: "הכנסת הבצק לתנור", desc: "מכוסה 20 דק׳ + חשוף 22 דק׳" },
      ready: { label: "הלחם מוכן" },
    },
    tooSoon: (minDate: string) => `המוקדם ביותר: ${minDate}`,
    startButton: "התחל בייק",
  },
  feedStage: {
    title: "האכלת הסטארטר",
    subtitle: "שלב הכנה",
    feedLabel: "האכל את הסטארטר",
    peakLabel: "הסטארטר יגיע לשיא",
    durationBridge: (hours: number) => `כ-${hours} שעות`,
    timeDisclaimer: "הזמן הוא הערכה — הסטארטר עצמו יגיד לך מתי הוא מוכן",
    readinessTitle: "איך יודעים שהסטארטר מוכן?",
    readinessSigns: [
      "השאור הוכפל בנפח",
      "רואים בועות בפנים",
      "ריח קצת חמצמץ ומתוק",
      "שקוע מעט בפסגה",
      "עובר מבחן ציפה (float test)",
    ] as readonly string[],
    timerLabel: "עד שיא הסטארטר",
    ctaButton: "הסטארטר מוכן — מתחיל לאפות!",
    bannerStage: "האכלת סטארטר",
  },
  validationCopy: {
    nameRequired: "שדה חובה",
    flourSumWrong: (current: number) =>
      `סה״כ הקמחים חייב להיות 100% (כרגע: ${current.toFixed(1)}%)`,
    hydrationRange: "הידרציה צריכה להיות בין 50% ל-100%",
    saltRange: "מלח צריך להיות בין 0% ל-5%",
    levainRange: "שאור צריך להיות בין 0% ל-40%",
    flourWeightRange: "משקל קמח חייב להיות בין 100g ל-1500g",
    tempRange: "טמפ׳ צריכה להיות בין 10°C ל-40°C",
    inclusionNameRequired: "שם התוספת לא יכול להיות ריק",
    inclusionAmountPositive: "כמות התוספת חייבת להיות חיובית",
  },
} as const;
